### ISSUE TITLE
Error thrown when first item added to dashboard

### ISSUE THREAD

**Issue by aaqsr** [waterloo-rocketry/omnibus#101]
When the dashboard first starts up and you select add item and select a series to be displayed, it does not add the item and instead throws this,
![image](https://user-images.githubusercontent.com/36773044/228996946-51848430-c051-4e62-8744-91ab4f9ca3ec.png)

Adding some debug statements to prompt_user (inside the for loop),
![image](https://user-images.githubusercontent.com/36773044/228997066-f8851238-16f3-4871-bc01-7d4c4c7fd823.png)
we see that for some reason the number of checkboxes seems to be less than the number of items. (Note the two numbers on top of the first screenshot).

This only occurs the first time the user is prompted for series and picks a series to display. The next time you add an item, it works perfectly, and the number of checkboxes and the number of items have the same length,
![image](https://user-images.githubusercontent.com/36773044/228997240-73d0fdbb-0d95-492e-a293-02b3734c3c15.png)

Even just opening and closing the prompt for which series to pick at the start fixes the bug and then any item can be added without bugs.

**Comment by AvKat** [comment]
I think this issue does not exists anymore in the UI restructure.
