### ISSUE TITLE
Timing Handler Using Python Async

### ISSUE THREAD

**Issue by Darth-Raazi** [waterloo-rocketry/omnibus#132]
We have a few widgets which need to do something every "X" amount of seconds. PyQt does have a timer for this, but it's not ideal as the timer drifts. Right now, we do some hacky stuff using on-data-update. I think it might be possible to spin up a thread to handle this using Python's async functionality

**Comment by BluCodeGH** [comment]
Async and threads are very rarely used in conjunction, and I don't think either are particularly good solutions here. What are the observed issues with Qt's timer?
