### ISSUE TITLE
Create GUI Tool for Omnibus Launcher

### ISSUE THREAD

**Issue by Darth-Raazi** [waterloo-rocketry/omnibus#139]
Dependent on #131 
---
New launcher is fully text/cli based, but it's more user friendly to select buttons than entering numbers. Goal: `launcher.py` opens a pop-up window that allows the user to select whatever sources and sinks they want. Window closes and the desired config launches.

**Comment by wxp02** [comment]
![image](https://github.com/waterloo-rocketry/omnibus/assets/83505161/cf86c2e2-80f5-4ed4-8745-a94d59891979)

![image](https://github.com/waterloo-rocketry/omnibus/assets/83505161/4f7938f2-a40b-494b-9636-2bff9334143c)

![image](https://github.com/waterloo-rocketry/omnibus/assets/83505161/70379566-1487-44a2-856b-01c9721c5d39)

Attached some screenshots on the demo GUI. Feel free to suggest any changes to make

**Comment by wxp02** [comment]
![image](https://github.com/waterloo-rocketry/omnibus/assets/83505161/c34a73c0-2f6e-4f86-af9d-f677673b2c85)

![image](https://github.com/waterloo-rocketry/omnibus/assets/83505161/5195169b-5713-4d11-b51e-ce4ba822587f)

![image](https://github.com/waterloo-rocketry/omnibus/assets/83505161/3789118b-697e-43ae-b2af-13c8833bbe6d)

Atatched some screenshot on the demo GUI version 2 created using PyQt. Feel free to suggest any changes to make

**Comment by Darth-Raazi** [comment]
That looks great, can you make the confirmation button similar to what we have on the `Omnibus Help` popup? Also change the title to `Omnibus Launcher`? 
![image](https://github.com/waterloo-rocketry/omnibus/assets/67076803/209798a9-2a17-461f-ba31-952b7169f9f2)

**Comment by wxp02** [comment]
Managed to resolve the button issue

- Instead of using QMainWindow, use QDialog instead
- Put button in QVBoxLayout

<img width="392" alt="image" src="https://github.com/waterloo-rocketry/omnibus/assets/83505161/1a274c80-ef8a-4485-a5d3-d263cacc3e57">
