### ISSUE TITLE
Add Log Files

### ISSUE THREAD

**Issue by Darth-Raazi** [waterloo-rocketry/omnibus#140]
Dependent on #131 
---
With the new omnibus launcher, `stdout` from each process is printed when you exit along with `stderr` if there is any. It would be better to have these be written to log files for each source/sink instead (ex. `dashboard.log`, `fakeni.log`).

**Comment by nitintejuja** [comment]
@Darth-Raazi Can we use python `logging`  library or just send all `stdout`logs to each source/sink log file ?

**Comment by Darth-Raazi** [comment]
Hi @nitintejuja, thanks for your interest but unfortunately this code is only to be worked on by members of the Waterloo Rocketry Design Team.
