### ISSUE TITLE
Dashboard Secure Coding Error

### ISSUE THREAD

**Issue by Darth-Raazi** [waterloo-rocketry/omnibus#155]
Dashboard (`sinks/dashboard/main.py`) is giving the following error:

![Image](https://github.com/waterloo-rocketry/omnibus/assets/67076803/fbe41382-cf4f-49e8-a41a-258e4a602c81)

Please investigate and determine the root cause.

**Comment by BluCodeGH** [comment]
A preliminary google implies this is MacOS specific, which is important to note. Is your python version potentially out of date?

**Comment by Darth-Raazi** [comment]
Thanks I'll take a look

**Comment by Darth-Raazi** [comment]
It went away lol. Closing
