### ISSUE TITLE
Gauge Item

### ISSUE THREAD

**Issue by Darth-Raazi** [waterloo-rocketry/omnibus#198]
For data coming from sensors such as a pressure transducer, we want a gauge item to easily see the value. It should be similar to a YAMCS gauge (see image below) with a needle going from one end to the other as the value increases, a numerical readout of the value below the gauge and a text label for the name of the sensor below that. This should all be one unit (move together, not be separable, etc.)

![Image](https://github.com/waterloo-rocketry/omnibus/assets/67076803/205ec247-c31e-40a0-875e-6deec486a2e0)

**Comment by patrick-gu** [comment]
Doesn't seem like there's an easy existing component we can use for this. There's this https://doc.qt.io/qt-5/qml-qtquick-extras-circulargauge.html but I don't think we can use it from Python

**Comment by patrick-gu** [comment]
Does the gauge need to have the gradient? Seems like it would be pretty complicated to make it that configurable. Also, I'm assuming that the gauge will just have a fixed limit which is configurable?
