### ISSUE TITLE
Implement log processing

### ISSUE THREAD

**Issue by BluCodeGH** [waterloo-rocketry/omnibus#22]
We need a good way to analyze the (very large: ~6GB, 400k msgs, 1 billion data point) logs. This could involve our own analysis tool or exporting (perhaps optionally downsampled) data to another tool. It would also be good to have a way to pan through the logs to find the interesting parts to export.

**Comment by jli35** [comment]
could you upload some snippets of the log (or just the entire thing) so we know what it contains.

**Comment by BluCodeGH** [comment]
The logs are msgpacked omnibus messages, see #23 for the implementation.

**Comment by BluCodeGH** [comment]
Migrated to https://app.clickup.com/t/1kqp4ac
