### ISSUE TITLE
Omnibus program on Mac may crash after reconnecting to network

### ISSUE THREAD

**Issue by zangjiucheng** [waterloo-rocketry/omnibus#241]
When I reconnect to the network or connect in a certain way, the software may die. Even restarting the software may not fix it and a reboot is required to fix the problem.

I can't pinpoint the problem with this error yet. But somehow it is network related. The current solution is to reboot the laptop.

**Reproduced (with a chance):** reconnected to the network several times and restarted the software, running on macOS (M1) and Python 3.12.3

[txtconsole.log](https://github.com/user-attachments/files/15859806/txtconsole.log)

```
  File "/Users/jiucheng/Dev/rocketry/omnibus/omnibus/omnibus.py", line 43, in __init__
    OmnibusCommunicator.server_ip = self._recv_ip()
                                    ^^^^^^^^^^^^^^^
  File "/Users/jiucheng/Dev/rocketry/omnibus/omnibus/omnibus.py", line 55, in _recv_ip
    sock.bind(('', server.BROADCAST_PORT))  # listen for broadcasts
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 48] Address already in use
```

**(Note: it's not just the txtconsole for any sink that shows the same error)**

**Comment by zangjiucheng** [comment]
I think this is the reason for reusing ports, should we add a feature that checks if a port is being used and then switches to another port?

**Comment by Darth-Raazi** [comment]
I had this issue too, it bothered me for so long. Turns out it's firewall stuff on macOS. See #171. I ended up just turning off my firewall, maybe you can find a way to whitelist Python/Omnibus or change our ports to make it work?

**Comment by zangjiucheng** [comment]
Oh, sorry I didn't find your issue post. Thanks for your recommend!
