### ISSUE TITLE
Standard display item sparkline scaling

### ISSUE THREAD

**Issue by patrick-gu** [waterloo-rocketry/omnibus#250]
See [this comment](https://github.com/waterloo-rocketry/omnibus/pull/244#pullrequestreview-2161531626)

**Comment by patrick-gu** [comment]
To be more clear, I meant that the sparkline doesn't center itself properly, and the data line remains near the bottom, which leaves it pretty unhelpful. If you can't reproduce it, then it may just be solved for some unrelated reason.

**Comment by zangjiucheng** [comment]
Since this issue is no longer recurring, I'll assume it's been fixed for some unrelated reason. This issue will be closed. (If come up again, we will open this again someday)

**Comment by zangjiucheng** [comment]
This happened again in ColdFlow test, gonna deep tracking on this

**Comment by ChrisYx511** [comment]
It seems to be happening at random, but I also don't know what version of omnibus @Pdada1 was running.
We really really need to make sure to ship a stable version of omnibus for every test.

**Comment by ChrisYx511** [comment]
I noticed that on branch 'wdr' (#179) which is a closed merge request, included a fix [9027722](https://github.com/waterloo-rocketry/omnibus/pull/179/commits/902772240cce724a28c60c3a01ce3e04f1976687). IDK if this is already integrated into main though.
Can someone have a look?

**Comment by zangjiucheng** [comment]
I think my implementation fix is more universal than the WDR fix :)
