### ISSUE TITLE
Calibration Tool

### ISSUE THREAD

**Issue by BluCodeGH** [waterloo-rocketry/omnibus#31]
We use a line of best fit based on a handful of measurements to calibrate most of our sensors. It would be great to have a sink that can make the calibration process easier, for example being able to enter a correct value and take a sample using an average of nearby samples, and then showing the samples and line of best fit on a plot.

**Comment by DevinLeamy** [comment]
Sounds like an interesting issue.

Correct me where I'm wrong:
- Currently, data is collected to calibrate tools using existing sinks in omnibus.
- A line of best fit is drawn from the data to help approximate the _ideal_ calibration.
- This new sink would take in sample data and correct data and would calibrate tools using some function of both data sets, which would be an improvement over the current line-of-best-fit approach.

Questions:
- Where are we sourcing the _"correct values"_?
- What tools are begin calibrated?
- And, what does this process look like now?

**Comment by BluCodeGH** [comment]
Migrated to https://app.clickup.com/t/1kqp4ga
